version: 2.1

jobs:
  plan:
    docker:
    - image: cimg/aws:2024.03
    steps:
    - checkout
    - run: 
        name: terraform plan
        command: |
          aws sts get-caller-identity
          pwd
          ls -al
          terraform init
          terraform plan
  apply:
    docker:
    - image: cimg/aws:2024.03
    steps:
    - checkout
    - run: 
        name: terraform plan
        command: |
          aws sts get-caller-identity
          pwd
          ls -al
          terraform init
          terraform apply -auto-approve
  

workflows:
  main:
    jobs:
    - plan:
        name: plan
        context: kasamajay-github
    - hold:
        type: approval
        name: hold
        requires:
        - "plan"
    - apply:
        name: apply
        context: kasamajay-github
  
