version: 2.1

jobs:
  create-ec2:
    docker:
    - image: cimg/aws:2024.03
    steps:
    - checkout
    - run: 
        name: aws sts
        command: |
          aws sts get-caller-identity
          pwd
          ls -al
          terraform init
          terraform plan

workflows:
  main:
    jobs:
    - create-ec2:
        context: kasamajay-github
  
