version: 2.1

jobs:
  create-ec2:
    docker:
    - image: amazon/aws-cli
    steps:
    - run: 
        name: aws sts
        command: |
          aws sts get-caller-identity
          terraform init
          terraform plan

workflows:
  main:
    jobs:
    - create-ec2:
        context: kasamajay-github
  
